# Python fundamentals

********************

### Print lines


In [2]:
# Print hello worls
print("Hello, World!")
print("let's go")


Hello, World!
let's go


In [1]:
print(10, 2, 15)

print()

print(10)
print(2)
print(15)

print()

print(10, end=' ')
print(2, end='')
print(15)

10 2 15

10
2
15

10 215


In [3]:
print(f'Ahmed is {20} years old')

Ahmed is 20 years old


In [4]:
print("Esraa is {} years old, while Ahmed is {} years old".format(25, 20))

Esraa is 25 years old, while Ahmed is 20 years old


In [5]:
print("Esraa is {1} years old, while Ahmed is {0} years old, fawzy is {other}, magda is {other}".format(25, 20, other = 50))

Esraa is 20 years old, while Ahmed is 25 years old, fawzy is 50, magda is 50


In [4]:
data = dict(age1 ="20", age2 ="25", any_other='50')

print("Esraa is {age1} years old, while Ahmed is {age2} years old, fawzy is {any_other}, magda is {any_other}".format(**data))

Esraa is 20 years old, while Ahmed is 25 years old, fawzy is 50, magda is 50


In [6]:
print("apple : %d" % 111.5) 
print("orange : %.2f, orange : %.1f , orange : %5.2f" % (111.5, 5.333, 5.333)) 

apple : 111
orange : 111.50, orange : 5.3 , orange :  5.33


In [11]:
string = " let's learn python"

print(string.center(40, '#'))
print()
print(string.ljust(40, ' '))
print()
print(string.rjust(40, '-'))

########## let's learn python###########

 let's learn python                     

--------------------- let's learn python


### Print system parameters

In [9]:
# print python version

import sys

print(sys.version)

3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)]


In [10]:
# print environment paths

print(sys.path)

['D:\\EYouth\\My Materials\\03) python', 'C:\\Users\\Hello\\AppData\\Local\\Programs\\Python\\Python310\\python310.zip', 'C:\\Users\\Hello\\AppData\\Local\\Programs\\Python\\Python310\\DLLs', 'C:\\Users\\Hello\\AppData\\Local\\Programs\\Python\\Python310\\lib', 'C:\\Users\\Hello\\AppData\\Local\\Programs\\Python\\Python310', '', 'C:\\Users\\Hello\\AppData\\Roaming\\Python\\Python310\\site-packages', 'C:\\Users\\Hello\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages', 'C:\\Users\\Hello\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\win32', 'C:\\Users\\Hello\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\win32\\lib', 'C:\\Users\\Hello\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\Pythonwin']


In [11]:
# print python modules

print(sys.modules)

{'sys': <module 'sys' (built-in)>, 'builtins': <module 'builtins' (built-in)>, '_frozen_importlib': <module '_frozen_importlib' (frozen)>, '_imp': <module '_imp' (built-in)>, '_thread': <module '_thread' (built-in)>, '_warnings': <module '_warnings' (built-in)>, '_weakref': <module '_weakref' (built-in)>, '_io': <module '_io' (built-in)>, 'marshal': <module 'marshal' (built-in)>, 'nt': <module 'nt' (built-in)>, 'winreg': <module 'winreg' (built-in)>, '_frozen_importlib_external': <module '_frozen_importlib_external' (frozen)>, 'time': <module 'time' (built-in)>, 'zipimport': <module 'zipimport' (frozen)>, '_codecs': <module '_codecs' (built-in)>, 'codecs': <module 'codecs' from 'C:\\Users\\Hello\\AppData\\Local\\Programs\\Python\\Python310\\lib\\codecs.py'>, 'encodings.aliases': <module 'encodings.aliases' from 'C:\\Users\\Hello\\AppData\\Local\\Programs\\Python\\Python310\\lib\\encodings\\aliases.py'>, 'encodings': <module 'encodings' from 'C:\\Users\\Hello\\AppData\\Local\\Programs\\

In [12]:
# print current default string encoding

print(sys.getdefaultencoding())

utf-8


In [53]:
import os

print(os.getcwd()) # get working directory

print()

print(os.cpu_count())


D:\EYouth\My Materials\03) python

16


## <font color=red> Note </font>
#### <font color=blue>utf-8: Unicode Transformation Format - 8-bit </font>
- character encoding capable of encoding all possible characters in Unicode
- The encoding is variable-length and uses 1 to 4 bytes for each character.
- compatible with ASCII

## Object reference

In [12]:
a = 50
b = a

print(a,b)
print(id(a), id(b))

# b = 100
# print(a,b)
# print(id(a), id(b))


50 50
1959583942416 1959583942416
50 100
1959583942416 1959583944016


In [16]:
a = a+10

print(a)
print(b)

60
50


## <font color=red> Note </font>
> The expression a + 10 creates a new integer object with the value 60.
<br>The variable a is updated to reference this new integer object 60.
<br>b still references the old integer object 50, which has not changed.

### Multiple assignment

In [15]:
x=y=z=50
a,b,c=5,10,15 
print(x)    
print(y)    
print(z)    
print(a)    
print(b)    
print(c)

print(id(a), id(b), id(c))
print(id(x), id(y), id(z))

50
50
50
5
10
15
1934792917360 1934792917520 1934792917680
1934792918800 1934792918800 1934792918800


### Data Types

In [16]:
print(type(5))

print()

print(type(-5))

print()


print(type(4.5))

print()

print(type(5+2j))

print()

print(35e3)
print(type(35e3))


<class 'int'>

<class 'int'>

<class 'float'>

<class 'complex'>

35000.0
<class 'float'>


In [17]:
print(type('h')) # single quote

print()

print(type("h")) # double quote

print()

print(type([5, 'h']))

print()

print(type((5, 6, 7)))

print()

print(type({1:5, 2:'h'}))

print()

print(type(True))

print()

print(type({'h', 5}))

print()

print(type(None))

<class 'str'>

<class 'str'>

<class 'list'>

<class 'tuple'>

<class 'dict'>

<class 'bool'>

<class 'set'>

<class 'NoneType'>


In [18]:
a = 5
print(float(a))
print(type(float(a)))

print()

a = 2.8
print(int(a))
print(type(int(a)))

print()

a = 3
print(complex(a))
print(type(complex(a)))

5.0
<class 'float'>

2
<class 'int'>

(3+0j)
<class 'complex'>


### check for types similarity

In [19]:
print(isinstance(5, int))
print(isinstance(5.0, int))

True
False


In [20]:
print(isinstance(5, float))
print(isinstance(5.0, float))

False
True


In [21]:
print(isinstance('5', str))
print(isinstance("5.0", str))
print(isinstance(5, str))

True
True
False


***

# <font color=orange> Random Module </font>

In [1]:
import random

In [68]:
# Generate random float number

print(random.random())

0.45663391985903345


In [70]:
# Generate random number within a range

print(random.randrange(3, 9))

7


In [58]:
# select random item from a list

mylist = ["dog", "cat", "fish"]

print(random.choice(mylist))
print()
print(random.choices(mylist, weights = [10, 1, 1], k = 14))

dog

['dog', 'dog', 'cat', 'dog', 'dog', 'dog', 'dog', 'dog', 'cat', 'dog', 'dog', 'dog', 'fish', 'dog']


In [59]:
# select random sample of a list

mylist = ["dog", "cat", "fish"]
x = random.sample(mylist, k=2)
print(mylist)
print(x)

['dog', 'cat', 'fish']
['cat', 'dog']


In [64]:
# reorder the list

mylist = ["apple", "banana", "cherry"]
random.shuffle(mylist) # passing by reference "with its memory location"  reference: memory location

print(mylist)

['banana', 'apple', 'cherry']


In [65]:
x = random.shuffle(mylist) 

print(x)

None


In [91]:
# get the exact random number each time

import random

random.seed(0)
print(random.random())

0.8444218515250481


***

# <font color=orange>if Conditions</font>

In [106]:
#assignment 
x = y = 5

print(x == y)

True


In [117]:
a = 201
b = 200


print(a > b) # bigger
print(a < b) # smaller
print(a == b) # equal or not in value
print(a >= b) # bigger than or equal
print(a <= b) # smaller than or equal
print(a != b) # not equal

True
False
False
True
False
True


In [92]:
a = 5
b = 6

if a+b == 11:
    print('11')
    
elif a+b == 12:
    print(12)

print()
if b - a == 1:
    print(1)
elif b - a == 2:
    print(2)

11

1


In [118]:
a = 200
b = 200
if b > a:
    print("b is greater than a")
elif a > b:
    print("a is greater than b")
elif a == b:
    print("a equals b")
else:
    print('NA')

a equals b


In [97]:
a,b = 5,6

print(id(a))
print(id(b))

2227832750448
2227832750480


In [98]:
a,b = 5,5

print(id(a))
print(id(b))

2227832750448
2227832750448


In [96]:
a,b = 5,6

if a == b:
    print('a equals b')

if a is b:
    print('a equals b')

In [99]:
a=b=5

if a == b:
    print("a equals b")

a equals b


In [103]:
a = [1, 2, 3] # index --> [0, 1, 2]
b = a # have the same reference "Memory loc"

if a is b:
    print("a equals b")

print()

b[1] = 5
print(a)
print(b)
if a is b: # is for reference 
    print("a equals b")
else:
    print('a is not equal b')
    
print()

b = a[1:3] 
print(a)
print(b)
if a is b:
    print("a equals b")
    
elif a is not b:
    print('a is not b')
    
# else:
#     print('NA')

a equals b

[1, 5, 3]
[1, 5, 3]
a equals b

[1, 5, 3]
[5, 3]
a is not b


In [140]:
'a'*5

'aaaaa'

In [160]:
x = "a"

x*2

'aa'

In [106]:
print("aa" == "a" * 2)

True


In [107]:
# print("aa" == "a" * 2)

print()

x = "a"*2 # 'aa'
print(f'x = {x}')
print()
print("aa" is x)

x = "a"
print('aa' == x*2) # aa = aa
print("aa" is x*2)


x = aa

True
True
False


<>:8: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:12: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:8: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:12: SyntaxWarning: "is" with a literal. Did you mean "=="?
C:\Users\hadyo\AppData\Local\Temp\ipykernel_11376\2820600696.py:8: SyntaxWarning: "is" with a literal. Did you mean "=="?
  print("aa" is x)
C:\Users\hadyo\AppData\Local\Temp\ipykernel_11376\2820600696.py:12: SyntaxWarning: "is" with a literal. Did you mean "=="?
  print("aa" is x*2)


In [115]:
x = 5

if -1:
    print('7')

7


In [ ]:
# True == -1, 1 "any non zero values"
# False == 0 "Zero value"

### short hand if

In [117]:
a = 50
b = 20

if a > b: print("a is greater than b")
elif a < b: print('')
else: print()

a is greater than b


### short hand if .. else,   known as <font color=red> Ternary operators </font>

In [120]:
a,b =20, 330

print("A") if a > b else print("B")

B


### multiple else statements

In [170]:
a = 330
b = 330

print("A") if a > b else print("a equals b") if a == b else print("B")


a equals b
a equals b


### And, Or & not

In [175]:
a = 200
b = 33
c = 500
if a > b and c > a:
    print("Both conditions are True")

print()

if a > b or a > c:
    print("At least one of the conditions is True")

print()

    
if not a<b:
    print("a is NOT smaller than b")

Both conditions are True

At least one of the conditions is True

a is NOT smaller than b


In [126]:
x = 6

if x > 5:
    print("Above five,")
    if x > 10:
        print("and also above 10!")
    else:
        print("but not above 10.")


Above five,
but not above 10.


# <font color=orange>Loops</font>

## while loops

In [127]:
i = 1
while i < 6:
    print(i)
    i += 1
    

1
2
3
4
5


In [40]:
# break

i = 1
while i < 6:
    print(i)
    if i == 3:
        break
    i += 1

1
2
3


In [193]:
# conitnue

i = 0
while i < 6:
    i += 1
    if i == 3:
        continue
    print(i)

1
2
4
5
6


In [202]:
flag = True

x = 0
while flag:
    x+=2
    print(x)
    if x == 10:
        flag = False

2
4
6
8
10


In [131]:
# else statement
i = 1
while i < 6:
    print(i)
    i += 1
else:
    print("i is no longer less than 6")
    i = 1

print()
print(i)

while i < 6:
    print(i)
    i += 1

1
2
3
4
5
i is no longer less than 6

1
1
2
3
4
5


 ##  for loops

In [132]:
fruits = ["cat", "dog", "fish"]

for x in fruits:
    print(x)

cat
dog
fish


In [137]:
fruits = ["cat", "dog", "fish"]

for i in range(len(fruits)):
    print(i, fruits[i])

0 cat
1 dog
2 fish


In [209]:
x = range(2, 6)
print(x)

range(2, 6)


In [135]:
# loop through range of numbers
for x in range(6):
    print(x)
print()

for x in range(2, 6):
    print(x)

0
1
2
3
4
5

2
3
4
5


In [139]:
# else in foor loops

for x in range(6): # 0 --> 5
    print(x)
else:
    print("Finally finished!")

print()
print(x)

Finally finished!

5


In [2]:
for x in range(6):
    i = 0
    print(x)

print()
print(x)
print(i)

0
1
2
3
4
5

5
0


## <font color=red> Note </font>
> #### <font color=blue>on using break </font>
Else statement will not be executed

In [ ]:
for i in range(3):
    print(i)
    if i == 15:
        break
    print(i+2)


In [145]:
for x in range(6):
    if x == 3: break
    print(x)
else:
    print("Finally finished!")

0
1
2


In [144]:
# nested for loops


adj = ["red", "big", "tasty"]
fruits = ["apple", "banana", "cherry"]

for x in adj:
    for y in fruits:
        print(x, y)

red apple
red banana
red cherry
big apple
big banana
big cherry
tasty apple
tasty banana
tasty cherry


In [152]:
for x in range(3): # intentionally not to use the counter
    print(id(x))
    for x in range(5):
        print(id(x))
        print(x)
    print(y)

2227832750288
2227832750288
0
2227832750320
1
2227832750352
2
2227832750384
3
2227832750416
4
Hello
2227832750320
2227832750288
0
2227832750320
1
2227832750352
2
2227832750384
3
2227832750416
4
Hello
2227832750352
2227832750288
0
2227832750320
1
2227832750352
2
2227832750384
3
2227832750416
4
Hello


In [151]:
y = 'Hello'

for _ in range(3): # intentionally not to use the counter
    print(id(_))
    for _ in range(5):
        print(id(_))
        print(_)
    print(y)


2227832750288
2227832750288
0
2227832750320
1
2227832750352
2
2227832750384
3
2227832750416
4
Hello
2227832750320
2227832750288
0
2227832750320
1
2227832750352
2
2227832750384
3
2227832750416
4
Hello
2227832750352
2227832750288
0
2227832750320
1
2227832750352
2
2227832750384
3
2227832750416
4
Hello


In [153]:
i = 'banana'
for _ in i:
    print(i)

banana
banana
banana
banana
banana
banana


### Take inputs

In [160]:
a = int(input())
b = int(input())
print(type(a))
print(type(b))

print(a)
print(b)
print(a+b)

 5
 6


<class 'int'>
<class 'int'>
5
6
11


In [157]:
a = int(input())
b = int(input())

print(type(a))
print(type(b))

print(f'a is {a}')
print(f'b is {b}')
print(f'a+b is {a+b}')

 5
 6


<class 'int'>
<class 'int'>
a is 5
b is 6
a+b is 11


In [170]:
g1 = 1
g2 = 2

a = "hello" + str(g2)
x = f'hello{g2}'

print(x)

hello2


***

# <font color=orange>Python Lists</font>

In [59]:
# ordered, changeable, and allow duplicate values.
ls = ["apple", 5, 5, 2.3, 1+2j, "h"]

print(ls)

['apple', 5, 5, 2.3, (1+2j), 'h']


In [60]:
# Get length
ls = ["apple", 5, 5, 2.3, 1+2j, "h"]

print(len(ls))

6


### Acess list items "List indexing"

In [64]:
# get specific items

ls = ['cat', 'dog', 'fish']

print(ls[1]) # get second item
print()
print(ls[2]) # get third item
print()
print(ls[0])  # get first item
print()
print(ls[-1])  # get last item
print()
print(ls[-2])  # get the item before the item

dog

fish

cat

fish

dog


In [65]:
# get third, fourth and fifth item

ls = ["apple", "banana", "cherry", "orange", "kiwi", "melon", "mango"]
print(ls[2:5])

['cherry', 'orange', 'kiwi']


In [66]:
# get the first four elements
ls = ["apple", "banana", "cherry", "orange", "kiwi", "melon", "mango"]
print(ls[:4])

['apple', 'banana', 'cherry', 'orange']


In [67]:
# get the items starting with the third item till the end
ls = ["apple", "banana", "cherry", "orange", "kiwi", "melon", "mango"]
print(ls[2:])

['cherry', 'orange', 'kiwi', 'melon', 'mango']


In [27]:
# get the last four items
ls = ["apple", "banana", "cherry", "orange", "kiwi", "melon", "mango"]
print(ls[-4:-1])

['orange', 'kiwi', 'melon']
[]


In [2]:
# get the last four items
ls = ["apple", "banana", "cherry", "orange", "kiwi", "melon", "mango"]
print(ls[-1:3])

[]


### Check item existance

In [28]:
ls = [1, 2, 3, 4, 5]
if 3 in ls:
    print("Yes, 3 is in the list")

Yes, 3 is in the list


### Change list items

In [75]:
# Change first item
ls = ['cat', 'dog', 'fish']
print(ls)

print()

print('after changing')
ls[0] = 'bird'
print(ls)

['cat', 'dog', 'fish']

after changing
['bird', 'dog', 'fish']


In [3]:
ls = ['cat', 'dog', 'fish']
# print(ls)
print(id(ls))

print()

print('after changing')
ls[0] = 'bird'
print(id(ls))
# print(ls)

2175062152832

after changing
2175062152832


In [29]:
ls = ['cat', 'dog', 'fish']
# print(ls)
print(id(ls[0]))

print()

print('after changing')
ls[0] = 'bird'
print(id(ls[0]))

2174998834672

after changing
2175061811504


In [4]:
# change range of items

ls = ['cat', 'dog', 'fish']
print(ls)
print(id(ls))

print()


print('after changing')
ls[0:2] = ['bird', 'cat']
print(ls)
print(id(ls))

print()
print('after changing and adding another item')
ls[0:2] = ['dog','bird', 'cat']
print(ls)
print(id(ls))

['cat', 'dog', 'fish']
2175062156224

after changing
['bird', 'cat', 'fish']
2175062156224

after changing and adding another item
['dog', 'bird', 'cat', 'fish']
2175062156224


### adding new items

In [30]:
ls = ['cat', 'dog', 'fish']
ls.append('bird')

print(ls)

['cat', 'dog', 'fish', 'bird']


In [33]:
ls = ['cat', 'dog', 'fish']
print(id(ls[0]))
ls.insert(0, 'bird')
print(id(ls[0]))
print(id(ls[1]))
print(ls)
print()

ls = ['cat', 'dog', 'fish']
ls.insert(1, 'bird')

print(ls)


2174998834672
2175061811504
2174998834672
['bird', 'cat', 'dog', 'fish']

['cat', 'bird', 'dog', 'fish']


In [34]:
ls1 = ['cat', 'dog', 'fish']
ls2 = ['bird', 'hamster']
tup3 = ('canary', 'turtle')

ls1.extend(ls2)

print(ls1)
print()

ls1.extend(tup3)
print(ls1)

ls1.extend(['butterfly'])
print(ls1)

ls1.extend('butterfly')
print(ls1)

['cat', 'dog', 'fish', 'bird', 'hamster']

['cat', 'dog', 'fish', 'bird', 'hamster', 'canary', 'turtle']
['cat', 'dog', 'fish', 'bird', 'hamster', 'canary', 'turtle', 'butterfly']
['cat', 'dog', 'fish', 'bird', 'hamster', 'canary', 'turtle', 'butterfly', 'b', 'u', 't', 't', 'e', 'r', 'f', 'l', 'y']


In [9]:
ls1 = ['cat', 'dog', 'fish']
ls2 = ['bird', 'hamster']

print(ls1+ls2)

['cat', 'dog', 'fish', 'bird', 'hamster']


In [10]:
ls1 = [1, 2, 3]
ls2 = [1, 2]

print(ls1+ls2)

[1, 2, 3, 1, 2]


### removing items

In [90]:
# remove last item

ls = ['cat', 'dog', 'fish', 'bird']
ls.remove('bird')

print(ls)

['cat', 'dog', 'fish']


In [11]:
# remove second item

ls = ['cat', 'dog', 'fish', 'bird']
ls.pop(1)

print(ls)

dog
['cat', 'fish', 'bird']


In [35]:
# pop Vs remove

ls = ['cat', 'dog', 'fish', 'bird']
second_item = ls.pop(1)

print(ls)
print(second_item)

['cat', 'fish', 'bird']
dog


In [95]:
# clear list

ls = ['cat', 'dog', 'fish', 'bird']
ls.clear()

print(ls)


[]


### list looping

In [98]:
ls = ['cat', 'dog', 'fish', 'bird']

for i in range(len(ls)):
    print(f'item index is {i} = {ls[i]}')

item index is 0 = cat
item index is 1 = dog
item index is 2 = fish
item index is 3 = bird


In [99]:
ls = ['cat', 'dog', 'fish', 'bird']

for pet in ls:
    print(pet)

cat
dog
fish
bird


In [14]:
ls = ['cat', 'dog', 'fish', 'bird']

for i, pet in enumerate(ls):
    print(i, pet)

0 cat
1 dog
2 fish
3 bird


In [18]:
list(enumerate(ls))

[(0, 'cat'), (1, 'dog'), (2, 'fish'), (3, 'bird')]

### List comprehension

In [21]:
ls = ['cat', 'dog', 'fish', 'bird']
print([x for x in ls])
[print(x) for x in ls]

['cat', 'dog', 'fish', 'bird']
cat
dog
fish
bird


[None, None, None, None]

In [25]:
ls = [x for x in range(10)]
print(ls)


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [38]:
# get fruits having a letter
fruits = ["apple", "banana", "cherry", "kiwi", "mango"]
newlist = []

for x in fruits:
    if "a" in x:
        newlist.append(x)

print(newlist)

# list comprehension
newlist = [x for x in fruits if "a" in x]

print(newlist)

['apple', 'banana', 'mango']
['apple', 'banana', 'mango']


## <font color=red> Note </font>
written as follow
>newlist = [expression for item in iterable if condition == True]

### List Sorting

In [107]:
# sort in ascending order

ls = [100, 50, 65, 82, 23]
ls.sort()
print(ls)

# sort in descending order
ls = [100, 50, 65, 82, 23]
ls.sort(reverse = True)
print(ls)

[23, 50, 65, 82, 100]
[100, 82, 65, 50, 23]


In [108]:
# list reversing

ls = [100, 50, 65, 82, 23]
ls.reverse()
print(ls)

[23, 82, 65, 50, 100]


# <font color=orange>Strings</font>

In [113]:
# Strings are arrays

a = "Hello, World!"
print(a[1])
print(a[5])
print(a[6])
print(a[-1])

for x in "banana":
    print(x)

e
,
 
!
b
a
n
a
n
a


In [115]:
# get number of letters

a = "banana"

print(len(a))

6


In [118]:
# Check word existance

txt = 'I will play football tomorrow'
print('football' in txt)
print('tennis' not in txt)

True
True


### slicing

In [123]:
b = "Hello, World!"
print(b[2:5])

print()

b = "Hello, World!"
print(b[:5])

print()

b = "Hello, World!"
print(b[2:])

print()

b = "Hello, World!"
print(b[-5:-2])

llo

Hello

llo, World!

orl


### string manipulation

In [125]:
a = "Hello, World!"
print(a.upper())

a = "Hello, World!"
print(a.lower())

HELLO, WORLD!
hello, world!


In [127]:
# remove white space in the beginin and ending of the string

a = " Hello, World! "
print(a.strip())

Hello, World!


In [129]:
# Replace letters

a = "Hello, World!"
print(a.replace("H", "J"))

Jello, World!


In [131]:
# split
a = "Hello, World!"
print(a.split(","))

['Hello', ' World!']


In [137]:
a ='HI'
print(a.isupper())

a = "hello, world! from my python code"
print(a.title())

a = 'hello'
b = 'world'

print(a + ' ' + b)

True
Hello, World! From My Python Code
hello world


### Escape characters

In [143]:
a = 'hello\nworld'
print(a)

a = 'hello world\b'
print(a)

a = 'hello\\world'
print(a)

a = 'hello\'world'
print(a)

a = 'hello\tworld'
print(a)

hello
world
hello world
hello\world
hello'world
hello	world


***

# <font color=orange>Python functions</font>

In [9]:
def my_function():
  print("Hello from a function")

my_function()

Hello from a function


In [11]:
def fullname(f_name, l_name):
    print(f_name + ' ' + l_name)

fullname('Ayman', 'Ali')

Ayman Ali


### Arbitrary arguments

In [45]:
def fullname(f_name, l_name):
    print(f_name + ' ' + l_name)

name = ['Ayman', 'Ali']
fullname(*name) # only one start for the list
print('or')
fullname(name[0], name[1])

Ayman Ali
or
Ayman Ali


In [16]:
def fullname(*names): #positional arguments
    full_name = ' '.join(names)
    print(full_name)

# Example usage
names = ['Ayman', 'Ali']
fullname(*names)

Ayman Ali


### keyword arguments and positional arguments

In [19]:
def print_details(**kwargs):
    for key, value in kwargs.items():
        print(f"{key}: {value}")

# Example usage
print_details(first_name='Ayman', last_name='Ali', age=30)
# print()
# print_details(Mango='Ayman', banana='Ali', apple=30)

first_name: Ayman
last_name: Ali
age: 30


In [22]:
def full_info(*args, **kwargs):
    print("Positional arguments:", args)
    print("Keyword arguments:", kwargs)

# Example usage
full_info('Ayman', 'Ali', age=30, city='Cairo')


Positional arguments: ('Ayman', 'Ali')
Keyword arguments: {'age': 30, 'city': 'Cairo'}


### Default value

In [27]:
def summation(n1 = 10, n2 = 20):
    print(n1+n2)

summation()
summation(5,6)

30
11


### Passing by value Vs passing by reference

In [33]:
def modify_value(x):
    x += 10
    return x

value = 5
value_modified = modify_value(value)
print(value)
print(value_modified)

5
15


In [32]:
def modify_list(lst):
    lst.append(4)

my_list = [1, 2, 3]
print(my_list)
modify_list(my_list)
print(my_list)

[1, 2, 3]
[1, 2, 3, 4]


## <font color=red> Note </font>

### Strings, integers, and tuples are <u>immutable</u> in Python (does not change)

### Lists, dictionaries, and sets are <u>mutable</u> in Python. (can be changed)

In [42]:
# Copying the list to a new list to stop passing by reference

def modify_list(lst):
    new_ls = lst[:]
    new_ls.append(4)
    return new_ls

my_list = [1, 2, 3]
print(my_list)

new_ls = modify_list(my_list)
print(my_list)
print(new_ls)

[1, 2, 3]
[1, 2, 3]
[1, 2, 3, 4]


# <font color=orange>NumPy</font>

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [2]:
type(arr)

numpy.ndarray

## <font color=red> Note </font>

#### A dimension in arrays is one level of array depth (nested arrays).

### nested array:
> #### Are arrays that have arrays as their elements.

### 0-D Arrays

In [3]:
import numpy as np

arr = np.array(42) # scalar value

print(arr)

42


## <font color=red> Note </font>

> #### 0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

### 1-D Arrays or uni-dimensional

In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


## <font color=red> Note </font>

> #### array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

### 2-D Arrays

In [4]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


## <font color=red> Note </font>

> #### An array that has 1-D arrays as its elements is called a 2-D array.
> #### These are often used to represent matrix

### 3-D Arrays

In [6]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


## <font color=red> Note </font>

> #### An array that has 2-D arrays (matrices) as its elements is called 3-D array.

## Check Number of Dimensions?

In [7]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


### Higher dimensional arrays

In [7]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


# Array indexing

### 1D array indexing


In [10]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[0])
print(arr[1])
print(arr[-1])


1
2
4


### 2D array indexing

In [10]:
import numpy as np

arr = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10]
])

print('2nd element on 1st row: ', arr[0, 1])

print('3rd element on 1st row: ', arr[0][3])

print('2nd element on 2nd row: ', arr[1, 1])

print('3rd element on 2nd row: ', arr[-1][3])

print('last element on last row: ', arr[-1, -1])


2nd element on 1st row:  2
2nd element on 1st row:  4
2nd element on 1st row:  7
2nd element on 1st row:  9
2nd element on 1st row:  10


In [9]:
_3d_array = np.array([
    [
        [1, 2, 3], #index = 0
        [4, 5, 6] # index = 1
    ], # index = 0
              
    [
        [7, 8, 9], # index = 0
        [11, 12, 13] # index = 1
    ] # index = 1
])

In [11]:
print(_3d_array[-1][-1][1])
print(_3d_array[1, 1, 1])
print(_3d_array[1][1][1])

print(_3d_array[-1, -1, 1])

print(_3d_array[1])

12
12
12
12
[[ 7  8  9]
 [11 12 13]]


### 3D array indexing

In [12]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])
"""
[0,  1,  2]
[2d, 1d, 0d]
"""

6


# Array indexing

### 1D array indexing

In [18]:
# get range of items

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])
print()
print(arr[:4])
print()
print(arr[3:10]) # We have just 7 elements How?


[2 3 4 5]

[1 2 3 4]

[4 5 6 7]


## Using steps

In [19]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [20]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

[1 3 5 7]


### 2D array indexing

In [21]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [26]:
arr = np.array([
    [
        [1, 2, 3, 4, 5],
        [6, 7, 8, 9, 10]
    ],
    
    [
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]
    ]
])

# index to get 12

print(arr[1, 0, 1])
print(arr[1, 1, 1])

# Data Types

In [27]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int32


In [28]:
import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype) # unicode string

<U6


In [29]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='S') # byte string

print(arr)
print(arr.dtype) # string of length 1

[b'1' b'2' b'3' b'4']
|S1


In [31]:
arr = np.array([1, 2, 3, 44], dtype='S') # will cast to S2
print(arr)
print(arr.dtype)

print()

arr = np.array([1, 2, 3, 400], dtype='S2') # will not cast
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'44']
|S2

[b'1' b'2' b'3' b'40']
|S2


In [40]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='i1')

print(arr)
print(arr.dtype)

arr = np.array([1, 2, 3, 4], dtype='int64')
print(arr)
print(arr.dtype)

# i1 = int8
# i2 = int16
# i4 = int32 (default)
# i8 = int64
####
# int8  --> 8 byte
# int16
# int32 (default)
# int64 

[1 2 3 4]
int8
[1 2 3 4]
int64


## Changing data types of arrays

In [44]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])
print(arr.dtype)

print()
newarr_i = arr.astype('i') # converting

print(newarr_i)
print(newarr_i.dtype)

print()
newarr_int = arr.astype('int64') # converting

print(newarr_int)
print(newarr_int.dtype)

float64

[1 2 3]
int32

[1 2 3]
int64


In [45]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [47]:
import numpy as np

arr = np.array([1, 0, 3, -5])
print(arr.dtype)

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

int32
[ True False  True  True]
bool


# Numpy copy

In [49]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42 # The copy SHOULD NOT be affected by the changes made to the original array.

print(arr.dtype)
print(arr)
print(x)
print(x.dtype)
print()

print(id(arr))
print(id(x))

int32
[42  2  3  4  5]
[1 2 3 4 5]
int32

1921409549296
1921409553136


# Numpy view

In [51]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr.dtype)
print(arr)
print(x)
print(x.dtype)

print()
print(id(arr))
print(id(x))

int32
[42  2  3  4  5]
[42  2  3  4  5]
int32

1921409549488
1921409549104


In [52]:
# make changes to the view

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


In [54]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


## <font color=red> Note </font>

> #### Copies owns the data

> #### views does not own the data

> ## to check owning:
> Attribute <u>base</u> that returns None if the array owns the data
>
> otherwise it will return the data of the main array

## Get array shape

In [56]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

# arr = np.array([[1, 2, 3, 4],
#                 [5, 6, 7, 8],
#                 [10,11,12,13]])

print(arr.shape)

(2, 4)


In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [64]:
# reshape from 1D to 2D

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)
print(newarr)
print(newarr.ndim)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
2


In [65]:
# reshape from 1D to 3D

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [68]:
# Will work??

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8]) # shape (1, 8)

newarr = arr.reshape(3, 3)

print(newarr)

## Array iterating

In [69]:
import numpy as np

arr = np.array([1, 2, 3])

for x in arr:
    print(x)

1
2
3


In [70]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [71]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [72]:
import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


In [73]:
# Iterating using steps

import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
    print(x)

1
3
5
7


## <font color=red> Note </font>

#### Slicing the Array: arr[:, ::2]

> : (colon before the comma) indicates that all rows are included.
>
> ::2 (colon after the comma) indicates that every second column is selected.

>So, arr[:, ::2] is a slice that includes all rows but only every second column from the array arr.

# Array joining

In [77]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))


[1 2 3 4 5 6]
[1 2 3]
[4 5 6]


In [78]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1) # Column by Column

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [79]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=0) # Row by row

print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [21]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]



# split

In [22]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [86]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr,3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [88]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)
print(newarr)
# newarr = np.array_split(arr, 5)
# print(newarr)
# newarr = np.array_split(arr, 6)
# print(newarr)
# newarr = np.array_split(arr, 7)
# print(newarr)
# newarr = np.array_split(arr, 8)
# print(newarr)


# print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


# Search

In [89]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4) # Return indices (element-wise operations) [False, False, False, True, False, T,T]

print(x)

(array([3, 5, 6], dtype=int64),)


In [95]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0) # Return indices: element-wise operations

print(x)

(array([1, 3, 5, 7], dtype=int64),)


### Advanced Indexing

In [98]:
for i in x:
    print(arr[i])

for x in np.nditer(x):
    print(x)

# print(arr[x])
# print()
# print(arr[[1,2,3]])

[2 4 6 8]

[2 3 4]


In [106]:
import numpy as np

arr = np.array([[1, 2], [3, 4]])

x = np.where(arr%2 == 0)

print(x)
print(arr[x])

(array([0, 1], dtype=int64), array([1, 1], dtype=int64))
[2 4]


## <font color=red> Note </font>

#### Element-wise operations

> Applies the condition element-wise to the input array.
>
> [False, True, False, True, False, True, False, True]
>
> Then it returns just the index of the true elements

# Sort

In [109]:
import numpy as np

arr = np.array([3, 2, 0, 1])

print(np.sort(arr))
print(arr)

[0 1 2 3]
[3 2 0 1]


In [30]:
# Sort types

import numpy as np

arr = np.array([3, 2, 0, 1])

print(np.sort(arr)) # default (Quick Sort) Preferred for general-purpose sorting due to its performance.

print((np.sort(arr, kind='heapsort'))) # Offers a different trade-off between stability and performance.

[0 1 2 3]
[0 1 2 3]


## <font color=red> Note </font>

#### Stability

> stability refers to the property where two equal elements retain their relative order after sorting.
>
> if two elements are considered equal based on the sorting criterion, their order in the output will be the same as their order in the input.

In [8]:
# what is the result???

import numpy as np

arr = np.array([True, False, True])

arr_sort = np.sort(arr)
print(arr_sort)
print(id(arr[0]))
print(id(arr_sort[1]))

[False  True  True]
140735729049936
140735729049936


### Check item existance

In [7]:
import numpy as np

arr1 = [1,2,3,4,5]
arr2 = [3,4]

print(np.in1d(arr1, arr2))
print()
print(np.isin(arr1, arr2))
print()
print(np.isin(arr2, arr1))

[False False  True  True False]

[False False  True  True False]

[ True  True]


C:\Users\Green\AppData\Local\Temp\ipykernel_4356\445977265.py:6: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  print(np.in1d(arr1, arr2))


# Get the non intersected items

In [115]:
import numpy as np

arr1 = [1,2,3,4,5]
arr2 = [3,4]

print(np.setdiff1d(arr1, arr2))
print(np.setdiff1d(arr2, arr1))

[1 2 5]
[]


### Get Unique items in a list (without repeatition)

In [3]:
import numpy as np

arr = np.array([1,1,2,3,3,4,3,5,9,10])

np.unique(arr)

array([ 1,  2,  3,  4,  5,  9, 10])

### Count the repitition of an item

In [6]:
import numpy as np

arr = np.array([1,1,2,3,3,4,3,5,9,10]) # element-wise operation: [False, False, False, True, True, False]

print(np.sum(arr == 3))

3


In [131]:
import numpy as np

arr = np.array([0,1,1,2,3,3,4,3,5,9,10])

print(np.count_nonzero(arr))
print(np.count_nonzero(arr == 3))

10
3


## <font color=red> Note </font>

np.sum(array == item_to_count)

is using the comparison operator
it will return a boolean list like this: [False, True, True, True, True, False, ...etc.] 

Then it will sum the boolean results Note that True = 1, False = 0.

So, the sum will be the occurnce of the value

### Insert new item

In [136]:
import numpy as np

arr = [1,2,3,4,5]

# Insert 10 at the beginning
arr = np.insert(arr, 0, 10)
print(arr)

# Insert 6 at the end
arr = np.append(arr, 6)
print(arr)

# Calculate the middle index
middle_index = len(arr) // 2

# Insert 33 at the middle
arr = np.insert(arr, middle_index, 33)

print(arr)

[10  1  2  3  4  5]
[10  1  2  3  4  5  6]
[10  1  2 33  3  4  5  6]


# Work with the index of the lists

In [19]:
# sort with keep track of the indices

arr = np.array([100, 50, 900, 500, 600, 400, 800])
            #    0    1   2    3    4    5   6
          #Sort: 1    0   5    3

print(np.argsort(arr)) # Gives the indices that would sort the array

[1 0 5 3 4 6 2]


In [137]:
# Get the index of the minimum value

arr = np.array([100, 50, 900, 500, 600, 400, 800])

print(np.argmin(arr))

1


In [138]:
# Get the index of the maximum value

arr = np.array([100, 50, 900, 500, 600, 400, 800])

print(np.argmax(arr))

2


# Partitioning

In [165]:
array = np.array([70, 50, 20, 30, 90, 60, 50, 40])
print(np.sort(array))
# Set position to 3, for example
# position = 5

# Partition the array
partitioned_array = np.partition(array, 4)

print(partitioned_array)

[20 30 40 50 50 60 70 90]
[20 30 40 50 50 60 90 70]


#### indices partitioning

In [25]:
import numpy as np

array = np.array([70, 50, 20, 30, -11, 60, 50, 40])

k = 3
partitioned_indices = np.argpartition(array, k)

print(partitioned_indices)  # Output: indices of the partitioned array

[4 2 3 7 6 1 5 0]
